#!/usr/bin/env python3
"""Fill in Homework 2 notebooks (paths relative to this file)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "DataFiles"


def save_nb(name: str, cells: list[dict]) -> None:
    p = ROOT / name
    nb = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "cells": cells,
    }
    p.write_text(json.dumps(nb, indent=1))
    print("Wrote", p)


# ---------------------------------------------------------------------------
# Part 2 — Count-Min Sketch (CIC-IDS / ISCX)
# ---------------------------------------------------------------------------
CMS_CELLS: list[dict] = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "In this section we will be using the Intrusion Detection Evaluation Dataset (CIC-IDS2017), a file of source-to-destination web traffic flows and testing how reliably Countmin Sketch can be used to identify DoS (Denial of Service) attacks.\n",
            "\n",
            "Modern intrusion detection systems operate under significant practical constraints. Network traffic arrives as a high-volume stream, often consisting of millions of flows per hour, making it infeasible to store and process all data exactly. At the same time, detecting malicious behavior—such as coordinated attacks targeting a specific destination—requires identifying unusual patterns in near real time.\n",
            "\n",
            "In this assignment, you will focus on detecting potential Denial of Service (DoS) behavior by analyzing source-to-destination communication patterns. Intuitively, DoS attacks often manifest as many requests originating from one or more sources and targeting a small set of destinations at unusually high frequencies.\n",
            "\n",
            "However, instead of relying on exact counting methods (which can be memory-intensive and slow at scale), you will use a Count-Min Sketch, an approximate data structure that provides memory-efficient frequency estimates with probabilistic error guarantees.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "from __future__ import annotations\n",
            "\n",
            "import hashlib\n",
            "import io\n",
            "import json\n",
            "import pickle\n",
            "import sys\n",
            "import warnings\n",
            "from dataclasses import dataclass\n",
            "from typing import Dict, List, MutableMapping, Set\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from matplotlib import pyplot as plt\n",
            "\n",
            "warnings.filterwarnings(\"ignore\")\n",
            "\n",
            "from pathlib import Path\n",
            "DATA = Path.cwd() / \"DataFiles\"\n",
            "CSV_PATH = str(DATA / \"Wednesday-workingHours.pcap_ISCX.csv\")\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "df = pd.read_csv(CSV_PATH, low_memory=False)\n",
            "df.columns = [col.lstrip() for col in df.columns]\n",
            "destips = df.groupby(by=[\"Destination IP\"], as_index=False)[\"Label\"].count()\n",
            "destips = destips.sort_values(by=\"Label\")\n",
            "df[\"attack\"] = 0\n",
            "df.loc[df[\"Label\"] != \"BENIGN\", \"attack\"] = 1\n",
            "attackers = df.groupby(by=[\"Source IP\"])[\"attack\"].max()\n",
            "\n",
            "# Exact (source, destination) flow counts\n",
            "flow_counts = df.groupby([\"Source IP\", \"Destination IP\"]).size().astype(np.int64)\n",
            "flow_dict = flow_counts.to_dict()\n",
            "buf = io.BytesIO()\n",
            "pickle.dump(flow_dict, buf)\n",
            "dictsize = int(buf.tell())\n",
            "print(\"Approximate pickle size of exact flow dictionary (bytes):\", dictsize)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "class CountMinSketch:\n",
            "    \"\"\"Count-Min Sketch for approximate frequency estimation.\"\"\"\n",
            "\n",
            "    def __init__(self, width: int = 2048, depth: int = 2) -> None:\n",
            "        self.width = int(width)\n",
            "        self.depth = int(depth)\n",
            "        self.table = np.zeros((self.depth, self.width), dtype=np.int64)\n",
            "        self._seeds = [\"dsthash\" + str(k) for k in range(self.depth)]\n",
            "\n",
            "    def _hash(self, key: str, row: int) -> int:\n",
            "        payload = f\"{self._seeds[row]}::{key}\".encode(\"utf-8\")\n",
            "        digest = hashlib.blake2b(payload, digest_size=8).digest()\n",
            "        return int.from_bytes(digest, byteorder=\"big\", signed=False) % self.width\n",
            "\n",
            "    def memory_bytes(self) -> int:\n",
            "        return int(self.table.nbytes)\n",
            "\n",
            "    def update(self, key: str, count: int = 1) -> None:\n",
            "        for row in range(self.depth):\n",
            "            col = self._hash(key, row)\n",
            "            self.table[row, col] += count\n",
            "\n",
            "    def estimate(self, key: str) -> int:\n",
            "        return int(min(self.table[row, self._hash(key, row)] for row in range(self.depth)))\n",
            "\n",
            "\n",
            "def build_destination_sketches(\n",
            "    df: pd.DataFrame,\n",
            "    width: int = 2048,\n",
            "    depth: int = 2,\n",
            ") -> MutableMapping[str, CountMinSketch]:\n",
            "    \"\"\"One Count-Min Sketch per destination IP, keyed by source IP.\"\"\"\n",
            "    required_columns = [\"Source IP\", \"Destination IP\", \"Label\"]\n",
            "    sketches_by_destination: MutableMapping[str, CountMinSketch] = {}\n",
            "    for src_ip, dst_ip, _label in df[required_columns].itertuples(index=False, name=None):\n",
            "        if pd.isna(src_ip) or pd.isna(dst_ip):\n",
            "            continue\n",
            "        src = str(src_ip).strip()\n",
            "        dst = str(dst_ip).strip()\n",
            "        if not src or not dst:\n",
            "            continue\n",
            "        sketch = sketches_by_destination.get(dst)\n",
            "        if sketch is None:\n",
            "            sketch = CountMinSketch(width=width, depth=depth)\n",
            "            sketches_by_destination[dst] = sketch\n",
            "        sketch.update(src, 1)\n",
            "    return sketches_by_destination\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "W0, D0 = 10, 2\n",
            "sketches_small = build_destination_sketches(df, width=W0, depth=D0)\n",
            "sketchSize = sum(s.memory_bytes() for s in sketches_small.values())\n",
            "df_mem = int(df.memory_usage(deep=True).sum())\n",
            "print(f\"Sketches (w={W0}, d={D0}) total table bytes:\", sketchSize)\n",
            "print(\"Pandas DataFrame deep memory (bytes):\", df_mem)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "TARGET = \"192.168.10.50\"\n",
            "sk_target = sketches_small[TARGET]\n",
            "\n",
            "sub = df[df[\"Destination IP\"].astype(str).str.strip() == TARGET]\n",
            "sources_here = sub[\"Source IP\"].astype(str).str.strip().unique()\n",
            "estimates = {s: sk_target.estimate(s) for s in sources_here}\n",
            "\n",
            "exact_sub = (\n",
            "    df[df[\"Destination IP\"].astype(str).str.strip() == TARGET]\n",
            "    .groupby(\"Source IP\")\n",
            "    .size()\n",
            "    .astype(int)\n",
            ")\n",
            "\n",
            "attack_mask = sub[\"Label\"].astype(str).str.strip().str.upper() != \"BENIGN\"\n",
            "attackSources = sorted(sub.loc[attack_mask, \"Source IP\"].astype(str).str.strip().unique())\n",
            "print(\"Attack source IPs (label not BENIGN):\", len(attackSources))\n",
            "print(attackSources[:20], \"...\" if len(attackSources) > 20 else \"\")\n",
            "\n",
            "NAttackers = len(attackSources)\n",
            "print(\"Unique attacking source IPs:\", NAttackers)\n",
            "\n",
            "exact_counts = exact_sub\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "THRESH = 1000\n",
            "\n",
            "est_counts = pd.Series({s: sk_target.estimate(s) for s in exact_counts.index.astype(str)})\n",
            "est_counts = est_counts.reindex(exact_counts.index)\n",
            "\n",
            "true_anom = exact_counts > THRESH\n",
            "pred_anom = est_counts > THRESH\n",
            "\n",
            "FalseNeg = int((true_anom & ~pred_anom).sum())\n",
            "FalsePos = int((~true_anom & pred_anom).sum())\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(10, 4))\n",
            "x = est_counts.values.astype(float)\n",
            "bins = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100]\n",
            "n, edges, patches = ax.hist(x, bins=bins, edgecolor=\"black\")\n",
            "attack_est = est_counts[exact_counts.index.isin(attackSources)]\n",
            "in_bin = (attack_est.values[:, None] >= edges[:-1]) & (attack_est.values[:, None] < edges[1:])\n",
            "shade_idx = np.where(in_bin.any(axis=0))[0]\n",
            "for i in shade_idx:\n",
            "    patches[i].set_facecolor(\"salmon\")\n",
            "ax.set_xlabel(\"Estimated flow count (CMS)\")\n",
            "ax.set_ylabel(\"Number of source IPs\")\n",
            "ax.set_title(f\"Destination {TARGET} — shaded bins contain ≥1 known attack source\")\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "print(\"False negatives (exact>1000 but estimate<=1000):\", FalseNeg)\n",
            "print(\"False positives (exact<=1000 but estimate>1000):\", FalsePos)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "What do your results in the previous graph suggest about the likelihood of a false negative when relying on countmin sketch in this way? How about the likelihood of a false positive?\n",
            "\n",
            "**Response (also in `BAX423_HW2_WriteUp.pdf`).** With a small width (10), the sketch has few buckets per row, so different sources collide and counts bleed upward. That makes **false positives** (inflated estimates above 1000) more likely than **false negatives** (underestimates), because Count-Min returns the minimum across rows and is biased toward **over**-estimating heavy hitters when collisions occur. Underestimation is still possible but less common under this bias pattern.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "W1, D1 = 10, 4\n",
            "sketches_d4 = build_destination_sketches(df, width=W1, depth=D1)\n",
            "sk4 = sketches_d4[TARGET]\n",
            "est4 = pd.Series({s: sk4.estimate(s) for s in exact_counts.index.astype(str)})\n",
            "est4 = est4.reindex(exact_counts.index)\n",
            "pred4 = est4 > THRESH\n",
            "true_anom = exact_counts > THRESH\n",
            "FalsePos2 = int((~true_anom & pred4).sum())\n",
            "print(\"False positives with depth=4, width=10:\", FalsePos2)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "# Empirical tuning: miscount >=1 on benign-volume sources (true count <= THRESH).\n",
            "\n",
            "def fp_rate_for(w: int, d: int) -> float:\n",
            "    sk = build_destination_sketches(df, width=w, depth=d)[TARGET]\n",
            "    est = np.array([sk.estimate(str(s)) for s in exact_counts.index], dtype=float)\n",
            "    true = exact_counts.values.astype(float)\n",
            "    benign = true <= THRESH\n",
            "    off = np.abs(est - true) >= 1\n",
            "    return float(np.mean(benign & off))\n",
            "\n",
            "\n",
            "FINALwidth, FINALdepth = 8192, 6\n",
            "for w, d in [(8192, 6), (12288, 6), (16384, 7), (24576, 7), (32768, 8)]:\n",
            "    r = fp_rate_for(w, d)\n",
            "    print(\"try\", w, d, \"benign miscount>=1 rate\", r)\n",
            "    if r < 0.005:\n",
            "        FINALwidth, FINALdepth = w, d\n",
            "        break\n",
            "else:\n",
            "    FINALwidth, FINALdepth = 32768, 8\n",
            "\n",
            "print(\"Chosen FINALwidth, FINALdepth:\", FINALwidth, FINALdepth, \"rate:\", fp_rate_for(FINALwidth, FINALdepth))\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "sk_final = build_destination_sketches(df, width=FINALwidth, depth=FINALdepth)[TARGET]\n",
            "est_f = pd.Series({s: sk_final.estimate(str(s)) for s in exact_counts.index.astype(str)})\n",
            "est_f = est_f.reindex(exact_counts.index)\n",
            "NAnomalies = int((est_f > THRESH).sum())\n",
            "print(\"Anomalies detected (estimate > 1000) with final CMS:\", NAnomalies)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "out = {\n",
            "    \"dictsize\": dictsize,\n",
            "    \"sketchSize\": sketchSize,\n",
            "    \"FalsePos\": FalsePos,\n",
            "    \"FalseNeg\": FalseNeg,\n",
            "    \"FalsePos2\": FalsePos2,\n",
            "    \"FINALwidth\": FINALwidth,\n",
            "    \"FINALdepth\": FINALdepth,\n",
            "    \"NAnomalies\": NAnomalies,\n",
            "}\n",
            "for k, v in list(out.items()):\n",
            "    if v is None:\n",
            "        raise ValueError(f\"Missing {k}\")\n",
            "with open(str(Path.cwd() / \"CMS.json\"), \"w\") as f:\n",
            "    json.dump(out, f, indent=2)\n",
            "print(\"Wrote CMS.json\")\n",
        ],
    },
]

save_nb("countminSketchHW.ipynb", CMS_CELLS)
